---
- name: Include installation tasks
  include_tasks: install.yml
  tags: install

- name: Include configuration tasks
  include_tasks: configure.yml
  tags: configure

- name: Include cron setup tasks
  include_tasks: setup_cron.yml
  tags: cron