all:
  children:
    backup_clients:
      hosts:
        devs_hors_infra:
          ansible_host: 10.0.1.10  
          ansible_user: root
          ansible_port: 22
          
        prod_hors_infra:
          ansible_host: 10.0.1.20
          ansible_user: root
          ansible_port: 22
          
        mgmt_server:
          ansible_host: 10.0.1.30
          ansible_user: root
          ansible_port: 22