#list les machines, maps  machines vers host groups 
#(les groupes ou les machines serons referencee sur le playbook later)
all:
  children:
    backup_clients:
      children:
        webservers:
          hosts:
            web01:
              backup_paths:
                - /var/www
                - /etc/nginx
                - /etc/letsencrypt
              backup_excludes:
                - "*.log"
                - "cache/*"
              backup_schedule: "0 2 * * *"  # 2 AM daily
              retention_daily: 7
              retention_weekly: 4
              retention_monthly: 6
            
            web02:
              backup_paths:
                - /var/www
                - /etc/apache2
              backup_schedule: "0 3 * * *"
              
        databases:
          hosts:
            db01:
              backup_paths:
                - /var/lib/postgresql/backups
                - /etc/postgresql
              backup_pre_script: "/usr/local/bin/pg_dump_all.sh"
              backup_schedule: "0 1 * * *"  # Before web backups
              retention_daily: 14
              retention_weekly: 8
              retention_monthly: 12
              
        fileservers:
          hosts:
            files01:
              backup_paths:
                - /data/shares
              backup_excludes:
                - "*.tmp"
                - ".Trash-*"
              backup_schedule: "0 4 * * *"
              retention_daily: 30