- name: Execute Backup Immediately
  hosts: backup_clients
  become: yes
  gather_facts: no
  
  tasks:
    - name: Display backup start
      debug:
        msg: "Starting immediate backup for {{ inventory_hostname }} ({{ restic_repo_name }})"
    
    - name: Run backup script manually
      shell: /usr/local/bin/restic-backup.sh
      register: backup_output
      async: 3600  

      
    - name: Display backup completion
      debug:
        msg: "✓ Backup completed for {{ inventory_hostname }}"